### ISSUE TITLE
prance compile fails with `KeyError: 'Cannot set with an empty path!'` when resolving external paths

### ISSUE THREAD

**Issue by ioggstream** [jfinkhaeuser/prance#22]
## Expected Behaviour

I expect:

  - Prance to compile referenced objects `{$ref: "http://foo.com/bar.yaml#/Object"}`

### Minimal Example Spec

https://github.com/teamdigitale/api-starter-kit/blob/master/openapi/simple.yaml.src

## Actual Behaviour

```
Processing "https://gist.githubusercontent.com/ioggstream/c0adc0e37f3a35b2fc97c5d5238ebdda/raw/91c353b5432cbba61cbb479f82f7d835c99df3be/simple.yml"...
 -> Resolving external references.
Traceback (most recent call last):
  File "/home/rpolli/workspace-py/api-starter-kit/.tox/py36/bin/prance", line 11, in <module>
    sys.exit(cli())
  File "/home/rpolli/workspace-py/api-starter-kit/.tox/py36/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/rpolli/workspace-py/api-starter-kit/.tox/py36/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/rpolli/workspace-py/api-starter-kit/.tox/py36/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/rpolli/workspace-py/api-starter-kit/.tox/py36/lib/python3.6/site-packages/prance/cli.py", line 103, in command_invoke
    original_invoke(ctx)
  File "/home/rpolli/workspace-py/api-starter-kit/.tox/py36/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rpolli/workspace-py/api-starter-kit/.tox/py36/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/rpolli/workspace-py/api-starter-kit/.tox/py36/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/rpolli/workspace-py/api-starter-kit/.tox/py36/lib/python3.6/site-packages/prance/cli.py", line 182, in validate
    __validate(parser, name)
  File "/home/rpolli/workspace-py/api-starter-kit/.tox/py36/lib/python3.6/site-packages/prance/cli.py", line 54, in __validate
    parser.parse()
  File "/home/rpolli/workspace-py/api-starter-kit/.tox/py36/lib/python3.6/site-packages/prance/__init__.py", line 133, in parse
    self._validate()
  File "/home/rpolli/workspace-py/api-starter-kit/.tox/py36/lib/python3.6/site-packages/prance/__init__.py", line 267, in _validate
    resolver.resolve_references()
  File "/home/rpolli/workspace-py/api-starter-kit/.tox/py36/lib/python3.6/site-packages/prance/util/resolver.py", line 72, in resolve_references
    self.specs = self._resolve_partial(self.parsed_url, self.specs, ())
  File "/home/rpolli/workspace-py/api-starter-kit/.tox/py36/lib/python3.6/site-packages/prance/util/resolver.py", line 164, in _resolve_partial
    recursions)))
  File "/home/rpolli/workspace-py/api-starter-kit/.tox/py36/lib/python3.6/site-packages/prance/util/resolver.py", line 106, in _dereferencing_iterator
    ref_value = self._dereference(ref_url, obj_path, next_recursions)
  File "/home/rpolli/workspace-py/api-starter-kit/.tox/py36/lib/python3.6/site-packages/prance/util/resolver.py", line 146, in _dereference
    value = self._resolve_partial(ref_url, value, recursions)
  File "/home/rpolli/workspace-py/api-starter-kit/.tox/py36/lib/python3.6/site-packages/prance/util/resolver.py", line 171, in _resolve_partial
    path_set(partial, list(path), value, create = True)
  File "/home/rpolli/workspace-py/api-starter-kit/.tox/py36/lib/python3.6/site-packages/prance/util/path.py", line 116, in path_set
    raise KeyError('Cannot set with an empty path!')
KeyError: 'Cannot set with an empty path!'

```

## Steps to Reproduce
```
prance compile --backend=openapi-spec-validator https://gist.githubusercontent.com/ioggstream/c0adc0e37f3a35b2fc97c5d5238ebdda/raw/91c353b5432cbba61cbb479f82f7d835c99df3be/simple.yml
```

## Environment
- OS: linux fedora 27
- Python version: 3.6
- Swagger/OpenAPI version used: 3.0.0
- Backend: openapi-spec-validator

## Note

This code can resolve references (but does not validate it). Maybe there's something you can reuse. 
https://github.com/teamdigitale/api-starter-kit/blob/master/scripts/openapi_resolver.py

@jfinkhaeuser

**Comment by jfinkhaeuser** [comment]
Thanks - will check it out!

**Comment by jfinkhaeuser** [comment]
@ioggstream Thanks - I have a fix, will work on a release.

The issue is that the items you reference are at the top level of the included file - nothing wrong with that, but it's not common in OpenAPI specs, where all objects are typically defined in their own namespace. As such, the tests didn't catch this edge case.

The fix, luckily, is simple enough and there's going to be a bugfix release as soon as I get to it!

**Comment by jfinkhaeuser** [comment]
Well, actually, the reason is more complex - never mind, the fix is in the works.

**Comment by ioggstream** [comment]
Thanks!
